---
title: "Case Study: Analiza danych o samochodach"
author: "Aleksander Pietrzak"
date: "`r Sys.Date()`"
output: html_document
---

```{r}
#| echo: false
#| message: false
#| warning: false
data(mtcars)
library(ggplot2)
library(plotly)
library(dplyr)
```



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

## Zadania do wykonania

### 1. Wczytanie i podstawowa eksploracja danych

```{r load_data}
# Wczytaj dane mtcars (są już dostępne w bazowym R)
data(mtcars)
samochody <- mtcars

# Wyświetl pierwsze 6 wierszy
head(samochody)

# Sprawdź strukturę danych
str(samochody)

# Ile jest wierszy w zbiorze danych?
nrow(samochody)

# Podsumowanie statystyczne
mtcars_summary <- mtcars %>%
  group_by(cyl) %>%
  summarise(
    avg_hp  = mean(hp),
    avg_mpg = mean(mpg),
    count   = n()
    )
mtcars_summary
```


### 2. Analiza z pakietem dplyr

```{r dplyr_analysis}
library(dplyr)

# Policz ile samochodów ma daną liczbę cylindrów
iczba_cyl <- mtcars %>%
count(cyl)          
liczba_cyl

# Stwórz podzbiór danych - tylko samochody z silnikiem V8 (8 cylindrów)
v8_cars <- mtcars %>%
  filter(cyl == 8)
v8_cars

# Ile jest samochodów z silnikiem V8?


# Filtrowanie  aut hp> 200 i sortowanie malejąco wg mpg


# Jaka jest średnia moc samochodu dla każdej liczby cylindrów?


# Które samochody mają najlepsze i najgorsze zużycie paliwa?
```

### 3. Wizualizacja danych

```{r visualization}
library(ggplot2)

# Wykres zużycia paliwa w zależności od liczby cylindrów (boxplot)
#| echo: false
#| fig-width: 10
#| fig-height: 6

mtcars_summary <- mtcars %>%
  group_by(cyl) %>%
  summarise(avg_hp = mean(hp),
            avg_mpg = mean(mpg),
            count = n())

ggplot(mtcars_summary, aes(x = factor(cyl), y = avg_hp, fill = factor(cyl))) +
  geom_col(alpha = 0.8, width = 0.6) +
  geom_text(aes(label = paste0(round(avg_hp), " HP\n(", count, " aut)")),
            vjust = -0.5, size = 5, fontface = "bold") +
  labs(title = "Średnia moc silnika według liczby cylindrów",
       x = "Liczba cylindrów",
       y = "Średnia moc (HP)") +
  theme_minimal(base_size = 14) +
  scale_fill_brewer(palette = "Spectral") +
  theme(legend.position = "none") +
  ylim(0, max(mtcars_summary$avg_hp) * 1.2)

# Scatter plot: moc vs zużycie paliwa
#| echo: false
#| fig-width: 10
#| fig-height: 6

ggplot(mtcars, aes(x = hp, y = mpg)) +
  geom_point(color = 'red') +
  labs(
    x = 'Moc (hp)',
    y = 'Zużycie paliwa (mpg)',
    title = 'Moc silnika vs zużycie paliwa'
    )
```




